spring:
    application:
        name: ace-monitor

server:
    port: 8764 #启动端口

security:
    user:
        name: whb
        password: 123456
        role: USER
eureka:
     instance:
        preferIpAddress: true
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          #defaultZone: http://localhost:8761/eureka/
          defaultZone: http://39.108.59.108:8761/eureka/